version: '3.8'
services:
  # HTTP mode service with Traefik
  onenote-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["-mode=http", "-port=8181"]
    restart: unless-stopped
    environment:
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-text}
      - CONTENT_LOG_LEVEL=${CONTENT_LOG_LEVEL:-INFO}
      - ONENOTE_MCP_CONFIG=configs/config.json
    ports:
      - "8181:8181"
    volumes:
      - ./configs:/app/configs:ro
      - tokens_volume:/app
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.onenote-mcp.rule=Host(`onenote-mcp.tehgibson.landq.net`)"
      - "traefik.http.services.onenote-mcp.loadbalancer.server.port=8181"

volumes:
  tokens_volume: 
